# Generated by Django 3.2.4 on 2021-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(db_column='req_id', primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=30)),
                ('user_nationality', models.CharField(max_length=30)),
                ('user_city', models.CharField(max_length=30)),
                ('user_state', models.CharField(max_length=30)),
                ('user_pincode', models.CharField(max_length=6)),
                ('user_qualification', models.CharField(max_length=30)),
                ('user_salary', models.IntegerField()),
                ('user_pannumber', models.CharField(max_length=10)),
            ],
        ),
    ]
